# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
formats: []

build:
  image: latest

sphinx:
   configuration: docs/source/conf.py
   builder: html

python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
