"""
This module contains API models.
"""
from __future__ import annotations

from .backgrounds import Background
from .backgrounds import SeasonalBackgroundSet
from .base import BaseModel
from .base import FrozenModel
from .beatmap import Beatmap
from .beatmap import BeatmapAvailability
from .beatmap import BeatmapCovers
from .beatmap import BeatmapDifficultyAttributes
from .beatmap import BeatmapFailtimes
from .beatmap import BeatmapHype
from .beatmap import BeatmapNominations
from .beatmap import BeatmapRankStatus
from .beatmap import Beatmapset
from .changelog import Build
from .changelog import ChangelogEntry
from .changelog import GithubUser
from .changelog import UpdateStream
from .changelog import Version
from .common import Achievement
from .common import Country
from .common import TimestampedCount
from .gamemode import Gamemode
from .mods import Mod
from .mods import Mods
from .news import NewsPost
from .performance import CatchPerformanceAttributes
from .performance import ManiaPerformanceAttributes
from .performance import OsuPerformanceAttributes
from .performance import PerformanceAttributes
from .performance import TaikoPerformanceAttributes
from .scopes import Scopes
from .score import Score
from .score import ScoreStatistics
from .score import ScoreWeight
from .spotllight import Spotlight
from .token import OAuthToken
from .user import User
from .user import UserAccountHistory
from .user import UserBadge
from .user import UserGradeCounts
from .user import UserGroup
from .user import UserKudosu
from .user import UserLevel
from .user import Userpage
from .user import UserProfileCover
from .user import UserProfileTournamentBanner
from .user import UserQueryType
from .user import UserRankHistoryElement
from .user import UserStats
from .wiki import WikiPage
