name: mypy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths:
    - 'aiosu/**.py'
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: GitHub Action for mypy
        uses: jpetrucciani/mypy-check@master
        with:
          path: ''
          requirements: ".[test]"
          mypy_flags: '--config-file pyproject.toml'
          python_version: "3.9"
